export const BROWSER_ICONS = {
  chrome: { icon: 'logos:chrome', label: 'Google Chrome' },
  chromium: { icon: 'logos:chromium', label: 'Chromium' },
  edge: { icon: 'logos:microsoft-edge', label: 'Microsoft Edge' },
  firefox: { icon: 'logos:firefox', label: 'Mozilla Firefox' },
  safari: { icon: 'logos:safari', label: 'Safari' },
  opera: { icon: 'logos:opera', label: 'Opera' },
  operaGX: { icon: 'simple-icons:operagx', label: 'Opera GX' },
  brave: { icon: 'logos:brave-icon', label: 'Brave' },
  arc: { icon: 'simple-icons:arc', label: 'Arc' },
  vivaldi: { icon: 'logos:vivaldi-icon', label: 'Vivaldi' },
  yandex: { icon: 'simple-icons:yandexbrowser', label: 'Yandex Browser' },
  samsung: { icon: 'simple-icons:samsunginternet', label: 'Samsung Internet' },
  duckduckgo: { icon: 'simple-icons:duckduckgo', label: 'DuckDuckGo Browser' },
  internetExplorer: { icon: 'logos:internet-explorer', label: 'Internet Explorer' },
  postman: { icon: 'logos:postman-icon', label: 'Postman' },
  insomnia: { icon: 'simple-icons:insomnia', label: 'Insomnia' },
  hoppscotch: { icon: 'simple-icons:hoppscotch', label: 'Hoppscotch' },
  thunderClient: { icon: 'mdi:lightning-bolt', label: 'Thunder Client' },
  curl: { icon: 'mdi:console', label: 'cURL' },
  wget: { icon: 'mdi:download', label: 'Wget' },
  axios: { icon: 'simple-icons:axios', label: 'Axios' },
  unknown: { icon: 'mdi:web', label: 'Unknown Browser' },
};