export const DEVICE_ICONS = {
  desktop: { icon: 'mdi:monitor', label: 'Desktop' },
  laptop: { icon: 'mdi:laptop', label: 'Laptop' },
  mobile: { icon: 'mdi:cellphone', label: 'Mobile' },
  phone: { icon: 'mdi:cellphone', label: 'Phone' },
  smartphone: { icon: 'mdi:cellphone', label: 'Smartphone' },
  tablet: { icon: 'mdi:tablet', label: 'Tablet' },
  tv: { icon: 'mdi:television', label: 'Smart TV' },
  watch: { icon: 'mdi:watch-variant', label: 'Smart Watch' },
  wearable: { icon: 'mdi:watch-variant', label: 'Wearable' },
  console: { icon: 'mdi:gamepad-variant', label: 'Gaming Console' },
  server: { icon: 'mdi:server', label: 'Server' },
  virtualMachine: { icon: 'mdi:cloud-outline', label: 'Virtual Machine' },
  bot: { icon: 'mdi:robot', label: 'Bot' },
  iot: { icon: 'mdi:access-point-network', label: 'IoT Device' },
  router: { icon: 'mdi:router-wireless', label: 'Router' },
  smartDisplay: { icon: 'mdi:monitor-dashboard', label: 'Smart Display' },
  smartSpeaker: { icon: 'mdi:speaker-wireless', label: 'Smart Speaker' },
  kiosk: { icon: 'mdi:kiosk', label: 'Kiosk' },
  unknown: { icon: 'mdi:devices', label: 'Unknown Device' },
};