export const OS_ICONS = {
  windows: { icon: 'logos:microsoft-windows', label: 'Windows' },
  macos: { icon: 'logos:apple', label: 'macOS' },
  ios: { icon: 'logos:apple', label: 'iOS' },
  ipados: { icon: 'logos:apple', label: 'iPadOS' },
  android: { icon: 'logos:android-icon', label: 'Android' },
  linux: { icon: 'logos:linux-tux', label: 'Linux' },
  ubuntu: { icon: 'logos:ubuntu', label: 'Ubuntu' },
  debian: { icon: 'logos:debian', label: 'Debian' },
  fedora: { icon: 'logos:fedora', label: 'Fedora' },
  arch: { icon: 'logos:archlinux', label: 'Arch Linux' },
  centos: { icon: 'logos:centos-icon', label: 'CentOS' },
  redhat: { icon: 'logos:redhat-icon', label: 'Red Hat Enterprise Linux' },
  kali: { icon: 'simple-icons:kalilinux', label: 'Kali Linux' },
  mint: { icon: 'logos:linuxmint', label: 'Linux Mint' },
  zorin: { icon: 'simple-icons:zorin', label: 'Zorin OS' },
  chromeos: { icon: 'logos:chrome', label: 'ChromeOS' },
  harmonyos: { icon: 'simple-icons:harmonyos', label: 'HarmonyOS' },
  freebsd: { icon: 'simple-icons:freebsd', label: 'FreeBSD' },
  openbsd: { icon: 'simple-icons:openbsd', label: 'OpenBSD' },
  solaris: { icon: 'mdi:server', label: 'Solaris' },
  unknown: { icon: 'mdi:laptop', label: 'Unknown OS' },
};